### ISSUE TITLE
Headless host

### ISSUE THREAD

**Issue by hferee** [Rolisteam/rolisteam#1]
It would be nice to be able to host a game on a headless server (ie. without requiring a graphical server).
This can be useful if all the participants have crappy internet connections, but they own a server with a good connection.

**Comment by obiwankennedy** [comment]
Yes, We plan to do it in the future release. But first, rolisteam network management must be improved.
So, It will take some time before this feature.

**Comment by hferee** [comment]
Thanks for the answer!
You should maybe put your own bugs and improvements here so that we have an idea of the progression, and maybe someone will contribute ;-)

**Comment by sioc-de-narf** [comment]
We need a password protection on this standalone.

**Comment by obiwankennedy** [comment]
it is done!

**Comment by sioc-de-narf** [comment]
Good :blush:

**Comment by develroo** [comment]
I would just like to weigh in here and say that if a headless version were to be available it would make a great candidate for a docker image. I am willing to give that a spin if it happens.

**Comment by obiwankennedy** [comment]
Yep, the server is already working. You have to compiled "up to date" source files.

**Comment by develroo** [comment]
Cool. Well I started building a Dockerfile but did not know what to launch the binary as or how to pass along variables. I was going to build it against Ubuntu 18.04 and pull down and compile the git version. 

Does that sound about right ?

**Comment by obiwankennedy** [comment]
You can read this documentation about the server: 
 http://anima.rolisteam.org/roliserver.html

It may helps.
