### ISSUE TITLE
Players can see maps

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#10]
Hi !

I tested the fresh new 1.7.0 version, and i have to report an unfortunate blocker :(

All the maps are visible to players with the "MD" view, but only when they are connected when the MD opens the map.

Context :

- 2 players : P1, P2 + the MD
- 3 maps, all masked to the players : M1, M2, M3

Steps to reproduce :

- MD starts the server
- MD opens M1
- P1 connects to the server
- P1 sees M1 all purple => OK
- MD opens M2
- P1 sees M2 with transparency => KO
- P2 connects to the server
- P2 sees both M1 and M2 all purple => OK
- MD opens M3
- P1 and P2 sees M3 with transparency => KO
- P1 disconnects
- P1 reconnects
- P1 sees M1, M2 and M3 all purple => OK

That's a big problem if the MD cannot open maps live. The players must not know how many maps they will have to deal with.

**Comment by obiwankennedy** [comment]
Bug confirmed!
The workaround before the true fix, is to repaint with mask over the map and cover the whole map.  
The transparency is not defined and the map is hidden from players.

**Comment by obiwankennedy** [comment]
https://github.com/Rolisteam/rolisteam/commit/c826b737cf95ae42c930aa097ff3a15fd873fdf8 fixs the issue.

**Comment by superllm** [comment]
Works perfectly on 1.7.1. Many thanks ! :+1:
