### ISSUE TITLE
Release source tarball lacks all the submodules

### ISSUE THREAD

**Issue by BrainDamage** [Rolisteam/rolisteam#101]
The source code tarball lacks all the git subomodules, including the character sheet editor, the dice roller, etc etc.
Currently the only way to get a complete build is to check out the tag in git and fetch the submodules.

**Comment by obiwankennedy** [comment]
You probably download source tarball from github ?
Because, those tarball are generated by github and they don't include submodule. 
however, you may get source code from official website: http://www.rolisteam.org/download.html
they contain submodules.
