### ISSUE TITLE
wiki.rolisteam.org is not available

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Rolisteam/rolisteam#105]
# Your configuration:
Rolisteam version: N/A
Operating System and version (remove irrelevant): 
*  Linux (Ubuntu 19.04)

Rolisteam Setting (remove irrelevant):  N/A

# What did you do ? (Explain each step from starting rolisteam to the issue)
- Browse <wiki.rolisteam.org>

# What did you expect to see ? (Make sentences and explains in details with words)
- Website loaded properly

#What did you get instead ? (Describe in details the issue) 
- Browser errors with "Can't find the server"
- `host wiki.rolisteam.org` returns `Host wiki.rolisteam.org not found: 3(NXDOMAIN)`

**Comment by obiwankennedy** [comment]
yes, I move out, my new apartment has no internet connection. 
In the worst case, it will be back in one month.
