### ISSUE TITLE
Links not really clickables

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#11]
Hi,

Rolisteam seems to convert links to HTML but the HTML is not displayed as a clickable link :

![ahref](https://cloud.githubusercontent.com/assets/13885977/9454004/f70503e2-4abe-11e5-99d4-a3fc7d9822eb.png)

**Comment by obiwankennedy** [comment]
Yes, you should only type: https://github.com/Rolisteam/rolisteam/issues/10
html in chat editor has been disabled. Html typing leaded to errors. 

Type in older version of rolisteam (such as 1.6.1) : <-something
It will cause some troubles.

**Comment by superllm** [comment]
The problem is i only sent a link (http://........), not HTML markup. Rolisteam converted it into HTML markup, but displays it as is :(

**Comment by obiwankennedy** [comment]
You want the ability to include link but hide the real url to keep the surprise or to set text to don't break the magic ?

**Comment by superllm** [comment]
Well, that could be interesting too, but that's not my point.

But as of the release notes said : "Les liens http sont maintenant cliquables"

I only sent an http link in the chat, alone, no HTML markup, just the URI. It displays as in the screenshot and is not clickable at all.

**Comment by obiwankennedy** [comment]
Ok, I reproduce the issue and fix it.

**Comment by superllm** [comment]
Works in 1.7.1. Thanks !
