### ISSUE TITLE
NPC Rtok Token: shape bug ?

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#111]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- click and drop the rtok file on a vmap
- right click on it and changed the form

#What did you expect to see ? (Make sentences and explains in details with words)
- I was expected to see my alternative token (png image of the same size as the avatar's one)

#What did you get instead ? (Describe in details the issue) 
-The avatar was replaced by the color choosen for that npc in the NPC Maker and the form's image wasn't displayed.

**Comment by obiwankennedy** [comment]
Redownload rolisteam v1.9, I fixed it.

**Comment by sioc-de-narf** [comment]
hum, shouldn't that be rolisteam v1.9.x (x<>0) then ?

**Comment by sioc-de-narf** [comment]
ok, fixed in it, but weird name / URI selection working

**Comment by obiwankennedy** [comment]
Yes, it should be.
You have to double click to set the path to image.
