### ISSUE TITLE
Zoom in character sheet

### ISSUE THREAD

**Issue by graham2071** [Rolisteam/rolisteam#114]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 
Operating System and version (remove irrelevant): 
*  Linux Mint 19.3. Use the AppImage 19.1

Rolisteam Setting (remove irrelevant):  
* GM and Server
* Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
I created a character with rcse. Background image size is 1653x2338. I load it with rolisteam and share it with a player. The character sheet opens up correctly, but I can't zoom in. The image is scaled, there are no scrolling bars. I can't find a way to zoom in and the character sheet is really hard to read.

#What did you expect to see ? (Make sentences and explains in details with words)
A way to zoom the character sheet and scroll bars.

#What did you get instead ? (Describe in details the issue) 
A scaled image. I can't find how to zoom in. Maybe I missed something.
![Rolisteam character sheet](https://user-images.githubusercontent.com/23586402/72221181-5f456900-3558-11ea-943b-3a223903060d.png)

Thanks for your help.

**Comment by obiwankennedy** [comment]
By default the zoom level in charactersheet is set by the size of the window. 
So, in portrait sheet, the height set the max (as it is shown on your screen shot).

In your case, there is 2 options:
First solution, open the character sheet with rcse and edit the properties ( Menu > Edition > Sheet Properties ), check **Sheet should keep the same size**.
and set the fixed scale to 1.0 first and regenerate the code with rcse.
Then, you can see the sheet as it will appear on rolisteam. You may able to scroll if it is needed (with mouse wheel, no scrollbar)

The second solution is an improvement of the first.
Additionally to the first solution, you can add a slider on the sheet to control the scale.
So you will have the possibility to change the size not by resizing the window but by controlling the slider. If you need code example, you can take a look to the warhammer sheet [here](https://github.com/Rolisteam/rolisteam-community-data/tree/master/charactersheets/fr/warhammer_v2)

**Comment by graham2071** [comment]
Huge thanks to you @obiwankennedy !
Adding a slider as default on all character sheets would be a nice improvement.

I'll try to submit a PR with Nephilim Legende character sheet to `rolisteam-community-data` when I finish it (may take some time ;-) ) if owners of the image (Mnemos) are ok.
