### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by vincentlaloux** [Rolisteam/rolisteam#119]
Bonjour,

Je souhaitais télécharger la dernière version de rolisteam pour Windows et Mac via :
[http://www.rolisteam.org/download](http://www.rolisteam.org/download)

Mais j'ai une page 404 not found.

Merci pour votre aide.
Bonne journée.

**Comment by obiwankennedy** [comment]
https://sourceforge.net/projects/rolisteam/files/1.9.2/

**Comment by vincentlaloux** [comment]
Un énorme merci !
