### ISSUE TITLE
The chat cuts words

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#12]
Hi,

The chat cuts words in the middle of them, when it reaches the border of the window :

![words](https://cloud.githubusercontent.com/assets/13885977/9454092/bbb297d6-4abf-11e5-971e-9d8c47970a2f.png)

Would be great to have a word warp :)

**Comment by obiwankennedy** [comment]
Yes, but I disable word warp because of bad performance of it. I will probably offer the user to change it as he wishes.

**Comment by obiwankennedy** [comment]
https://github.com/Rolisteam/rolisteam/commit/fce2a3020cf89e33acc02c9310d70190973791b0 fixes the issue.

**Comment by superllm** [comment]
Works in 1.7.1. Thanks !
