### ISSUE TITLE
Error in the public network link.

### ISSUE THREAD

**Issue by Pierstoval** [Rolisteam/rolisteam#122]
Rolisteam version: 1.9.2
Operating System and version (remove irrelevant): Windows 10
Rolisteam Setting (remove irrelevant):  GM Server

### What did you do ? (Explain each step from starting rolisteam to the issue)
- Fresh install
- Start rolisteam
- IP address default set to `localhost` (seems strange to me)
- Click on `Network` > `Copy connection link`

### What did you expect to see ? (Make sentences and explains in details with words)
Some kind of `rolisteam://ip` address

### What did you get instead ? (Describe in details the issue) 
This:
```
21:22:49 - Search - Pierstoval vient de rejoindre la partie.
21:22:49 - Feature - Adresse IP du serveur:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://rolisteam.org/ip.php">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at www.rolisteam.org Port 80</address>
</body></html>

Port:6660
```

For the debug:

If I do `curl -i https://rolisteam.org/ip.php` I get this:

```
$ curl -i https://rolisteam.org/ip.php
HTTP/2 200
date: Thu, 02 Apr 2020 19:25:05 GMT
server: Apache/2.4.29 (Ubuntu)
cache-control: max-age=0
expires: Thu, 02 Apr 2020 19:25:05 GMT
vary: Accept-Encoding
strict-transport-security: max-age=15768000
referrer-policy: strict-origin-when-cross-origin
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: sameorigin
content-type: text/html; charset=UTF-8

{ my ip address }
```

This part works.

However, the Rolisteam client seems to use `HTTP` instead of `HTTPS`, because I tried doing `curl -i http://rolisteam.org/ip.php` and it gives me this:

```
$ curl -i http://rolisteam.org/ip.php
HTTP/1.1 301 Moved Permanently
Date: Thu, 02 Apr 2020 19:25:33 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://rolisteam.org/ip.php
Cache-Control: max-age=0
Expires: Thu, 02 Apr 2020 19:25:33 GMT
Content-Length: 315
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://rolisteam.org/ip.php">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at rolisteam.org Port 80</address>
</body></html>
```

So, probably the backend needs some kind of change? 😉

**Comment by obiwankennedy** [comment]
yes yes, the website have been rehosted and it is https now.
