### ISSUE TITLE
bug: players can change parameters on vmap

### ISSUE THREAD

**Issue by osfrance** [Rolisteam/rolisteam#123]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.9.2
Operating System and version (remove irrelevant): 
*  Windows 7

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- load vmap
-
-

#What did you expect to see ? (Make sentences and explains in details with words)
- players can change vmap visibility (none, fog of war, all)
- players can change vmap right (gm only, players can move, all)
-

#What did you get instead ? (Describe in details the issue) 
-
-
-

**Comment by obiwankennedy** [comment]
I can't reproduce it. 
Are you sure all your players have the latest version ?
I have no access to any control to change visibility or permission.

**Comment by osfrance** [comment]
I mount a second W7 VM with rolisteam 1.9.2, I'll try to this and I back to you my results...

**Comment by osfrance** [comment]
I don't reproduce this too... I don"t know how my players had sow all the map ... (perhaps my map was in all permissions ...)
Sorry for this bad Bug issue ... :-|

**Comment by obiwankennedy** [comment]
Perhaps you player try to connect as GM and then some widget are still displayed or somethings.

**Comment by osfrance** [comment]
Yes perhaps... thanks for help !
