### ISSUE TITLE
Clarifying invent vs github

### ISSUE THREAD

**Issue by cblegare** [Rolisteam/rolisteam#126]
Hello there and thank you for this project!

Before I settle on a open source VTT alternative, I look for ways to contribute.  I was confused by the clone for this repo on Invent, especially since issues were not migrated with the source.

Could you clarify a bit which repo is used in which context?

---

Bonjour! Laissez-moi d'abord vous remercier pour ce projet!

En cherchant des alternatives d'outils pour mes parties de jeu de rôles, je vérifie aussi si je pourrai contribuer aux projets. J'ai trouvé ce repo et son équivalent sur Invent et je n'ai pas trouvé plus d'explications. D'autant plus que les _issues_ n'avaient pas été migrées elles aussi.

Pourriez-vous clarifier vous intentions avec Github et Invent s'il-vous-plaît?

**Comment by obiwankennedy** [comment]
Bonjour, Merci de votre intérêts. 

Depuis peu, le projet Rolisteam est devenu un projet KDE, c'est pour cela qu'il a migré vers invent.kde.org, c'est le dépôt officiel. J'essaie de pousser les utilisateurs à n'utiliser que le invent. 

Cependant, pour offrir un peu de visibilité au projet, je continue de mettre à jour les dépôt github. 
avec le temps, je prendrais peut-être des décisions plus radicale pour pousser les gens à utiliser invent. 

Pour la migration des issues, si il existe une solution pour le faire automatiquement, je suis preneur et je ne savais pas que cela existait. 
Invent permet actuellement d'ouvrir des issues, je demande aux gros contributeurs de passer par la. 
Le site officiel du projet, renvoie vers invent mais des liens vers github existent encore, il faut que je prenne le temps de les supprimer.

Pour répondre à la question, j'ai voulu rendre la transition douce entre github et invent. 
On se rapproche de invent et on s'éloigne de github.

**Comment by cblegare** [comment]
Merci, ça répond à la question.

Pour les issues et autres, c'est à la création du projet: https://docs.gitlab.com/ee/user/project/import/github.html

Pour demander à Gitlab de mettre à jour Github https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html

Tout ça ensemble implique une migration plutôt «dure» par contre.  

Je vous remercie pour votre temps!
