### ISSUE TITLE
Roliserver - pas de log

### ISSUE THREAD

**Issue by EllimacN** [Rolisteam/rolisteam#127]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.9.2
Operating System and version: 
*  Windows 10 : client (rolisteam)
*  Debian 10 : server (roliserver) (accès via ssh, pas de bureau)

J'ai suivi la documentation pour mettre en place un serveur **roliserver** :
1) Récupération des sources
2) Compilation de roliserver uniquement (pas besoin du client)
A noter ici que dans la documentation les dépendances suivantes ne m'ont pas suffit
`sudo apt-get install qt5-qmake libqt5network5 libqt5core5a`
J'ai ajouté `qt5-default qml libqt5qml5` en plus. Mais je me suis débrouillé.

3) Configuration du serveur
- Création du fichier de config
- Génération des mots de passe
- Configuration de la log (niveau + fichier)
- Mise en place du service (systemctl)

Bref tout s'est bien passé. Le serveur démarre et j'arrive à me connecter dessus.
Avec des amis, nous avons réussi à nous y connectés à plusieurs. Nous avons rencontré quelques déboires en particulier pour le MJ mais ce n'est pas le sujet ici.

En voulant récupérer les logs du serveur pour essayer de voir quels étaient les déboires (cités plus haut) afin d'éventuellement soumettre une requête : pas de log.
Le fichier de log a bien été créé mais il est totalement vide.

J'ai refait des essais en testant les 4 niveaux de log voir si ça changeait quelque chose, sans succès.
Lorsque je démarre le serveur via le service ou à la main `roliserver -c <configFile>` le fichier de log se créé bien mais ne se remplit pas.
Lorsque je lance manuellement, roliserver garde la main sur la console et là je vois bien les logs défiler.

Si quelqu'un a une idée sur cette situation, je suis preneur.
Est-ce qu'il me manquerait une dépendance en particulier ?

**Comment by obiwankennedy** [comment]
Effectivement, il est pas impossible que les log déconne, Il me semble que j'ai du retoucher la fonctionnalité juste avant la sortie car elle posait problème. 
Pour ma part, j'ai configuré ma règle systemd pour gérer les log. Je peux du coup, voir les log du serveur grâce à: **journalctl -f**


Pour le problème, je me suis rendu compte d'un petit bug assez embêtant pouvant empêcher la connexion de MJ. 
Le mauvais code:
```cpp
    if(hasNoClient())
    {
        clearData();
    }
    else if((m_currentGm != nullptr) && (m_currentGm == client))
    {
        findNewGM();
    }
```

le bon (suppression du else):
```cpp
    if(hasNoClient())
    {
        clearData();
    }
    if((m_currentGm != nullptr) && (m_currentGm == client))
    {
        findNewGM();
    }
```

**Comment by EllimacN** [comment]
Merci pour la réponse rapide et complète.

- Je n'avais pas pensé à **journalctl**, je ne suis pas un pro de systemd :p. Merci pour l'info, ça me sera bien utile et sans doute pas que pour rolisteam :).

- Effectivement, notre MJ a rencontré des soucis de connexions. Nous avons constaté que s'il ne se connectait pas en premier, il n'arrivait pas à rejoindre la partie.
Hélas, je n'ai pas réussi à reproduire le problème par moi même (avec plusieurs clients rolisteam depuis le même PC), je ne sais donc pas exactement quel est le critère qui a causé l'erreur.
J'ai appliqué le correctif sur le code et recompiler mon serveur. Tout semble fonctionner dans l'immédiat. Nous verrons lors de notre prochaine session comment ça se passe.
Nous commençons tout juste à utiliser rolisteam pour nos parties :).

Super boulot en tout cas, bravo :).
