### ISSUE TITLE
roliserver - command not found

### ISSUE THREAD

**Issue by kharidiron** [Rolisteam/rolisteam#128]
#Your configuration:
Rolisteam version: 1.8.2ubuntu2
Operating System and version: Ubuntu 18.04.3 LTS

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Followed instructions to install Rolisteam via PPA on Ubuntu server.
- Attempted to launch roliserver

#What did you expect to see ? (Make sentences and explains in details with words)
- Either startup, or exit state demonstrating command-line usage

#What did you get instead ? (Describe in details the issue) 
- `roliserver: command not found`

I was naively hoping the server would have been included in the PPA bundle. If I am making a mistake, or if it is documented somewhere that I need to compile from source to get the server, sorry I somehow missed that. >_<

**Comment by obiwankennedy** [comment]
Hello, 

Ubuntu 18.04.3 is too old to have package release of Rolisteam v1.9 (which bring roliserver).

**Comment by kharidiron** [comment]
Oh... Well, that would definitely explain it. >_<

Thanks for clearing that up.
