### ISSUE TITLE
Rolisteam crashes when a player joins a game with "big" map file

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#13]
Hi,

Rolisteam seems to crash when a player joins a game with an opened map which can be considered as "big".

For the test, we used a map of 1,9 MB. When the player was in the game and the MD opened it, no problem. The player disconnected/reconnected to the game and Rolisteam instantly crashed.

All the opened maps weighed less than 3 MB. When the MD closed the 1,9 MB map, the player's Rolisteam did not crash anymore.

Tested on Windows 7 Ultimate (player side) and Debian 8 (MD side).

I know i opened a lot of issues in a row, but thanks for the great work though :)

**Comment by obiwankennedy** [comment]
Could you give a copy of that map ?
It will be great if I can test on my side.

It is always good to see some people interested in rolisteam. I prefere people who said to me where the problems are instead of keeping them to themselves. It does not help.

**Comment by obiwankennedy** [comment]
I tested loading a picture (5.9 MB) as map. Connect to the server, disconnect and reconnect. I did not get a crash.

**Comment by superllm** [comment]
Cannot reproduce in 1.7.1, neither on a clean install of 1.7.0.
