### ISSUE TITLE
Roliserver: howto ?

### ISSUE THREAD

**Issue by menestrwell** [Rolisteam/rolisteam#133]
Bonjour, 

Pour faire un roliserver, j'ai juste à créer un service ?
Ou bien il y a un .deb ? 
Une fois rolisteam installé, je n'avais pas d'application roliserver. 

J'avoue ne pas comprendre comment le mettre en place malgré la doc.

https://doc.rolisteam.org/pages/roliserver-fr.html

**Comment by obiwankennedy** [comment]
Oui, il n'y a pas encore trop de distribution binaire du serveur standalone. Il faut le compiler mais faire un deb devrait pas être trop dur.

**Comment by menestrwell** [comment]
ok :)
