### ISSUE TITLE
Rolisteam 1.9.3 - Ubuntu - fiche personnage blanche

### ISSUE THREAD

**Issue by menestrwell** [Rolisteam/rolisteam#134]
Bonjour

J'ai refais une fiche de perso (en fait la fiche de dés pour Starwars originellement au format RCSE1.8.2) au format RCSE1.9.3 avec le RCSE AppImage dernièrement mis à dispo

Le rendu fonctionne plutôt bien
![image](https://user-images.githubusercontent.com/75116332/102015747-aa19c300-3d5d-11eb-832a-8375297f811b.png)

Mais dans Rolisteam (deb 1.9.2 ou AppImage-1.9.3), le rendu ne se fait pas.
![image](https://user-images.githubusercontent.com/75116332/102015781-df261580-3d5d-11eb-92c4-b56f712876fd.png)

Au niveau des logs (via deb 1.9.2)
![image](https://user-images.githubusercontent.com/75116332/102015867-578cd680-3d5e-11eb-87f2-43b3e6363224.png)

Au niveau des logs bis (via AppImage 1.9.3)
![image](https://user-images.githubusercontent.com/75116332/102015907-8014d080-3d5e-11eb-93a8-cb83fffafe5b.png)

Note : 
J'ai ceci car j'ai fermé les applis un peu brutalement.
![image](https://user-images.githubusercontent.com/75116332/102015949-b2bec900-3d5e-11eb-803c-a79eacf5d196.png)

Voici le fichier RCSE en question
[starwars-1.9.rcs.zip](https://github.com/Rolisteam/rolisteam/files/5684827/starwars-1.9.rcs.zip)

En attendant, je n'arrive pas à comprendre pourquoi la fiche n'a pas de rendu dans rolisteam :disappointed: 

Si vous avez une idée ...

**Comment by obiwankennedy** [comment]
Il faut partager la fiche avec un joueur pour déclencher l'affichage.

**Comment by menestrwell** [comment]
J'ai fait le test de partage :
- de mon côté : affichage comme j'avais mis précédemment
- du côté de mon interlocuteur : rien, pas même dans la partie ressources

Ce qui me semble étrange c'est que dans la version 1.8.x, il n'y avait pas besoin de partager pour afficher dans rolisteam. ouvrir une fiche (même sans avoir d'autres joueurs) permettait de la visualiser

![image](https://user-images.githubusercontent.com/75116332/102182954-603ff280-3ead-11eb-90e2-31ead2cf97df.png)

Je me suis donc naturellement dit que ça devait être la même chose pour la version 1.9.x

**Comment by menestrwell** [comment]
C'est comme s'il me manquait des libs

Je sais que ce n'est pas compatible, mais j'aime bien faire ce genre de test:
Ouverture de la fiche perso (v1.9.x) dans rolisteam (v1.8.x - AppImage) 
J'ai le même résultat, à ceci prêt que j'ai des messages qui me disent qu'il manque QtQuick.Controls 2.3 (logique)

![image](https://user-images.githubusercontent.com/75116332/102183641-700c0680-3eae-11eb-8158-b656ec97001f.png)


Du coup, ne manquerait il pas dans la version 1.9.x quelque dépendances que j'ignore et qui empêchent le rendu ou le partage ? (ou les deux ? )

**Comment by obiwankennedy** [comment]
Ça marche très bien pour moi.

![test_ticket_134](https://user-images.githubusercontent.com/69177/102213520-2552b480-3ed7-11eb-9562-5c0a6d5108cc.gif)

**Comment by menestrwell** [comment]
Okayyyyy merci pour la démo :smiley: 

Bon, normalement le joueur devrait voir aussi les symboles. Mais je pense que ça vient du fait qu'ils sont hébergés et non dans la fiche elle même, je vais changer ça :smile: 
Merci encore

**Comment by menestrwell** [comment]
Du coup je viens de faire un test avec d'un côté la 1.9.3 .deb (MJ) 
et de l'autre 1.9.3 (appImage) 

Le partage se fait bien, j'ai bien le visuel (maintenant que j'ai compris comment faire)
Ceci étant, l'affichage dans le fichier AppImage ne se fait pas car : 

![image](https://user-images.githubusercontent.com/75116332/102227376-c8142e80-3ee9-11eb-8095-caa63955eb0c.png)

```
15:22:31 - Error - file:///tmp/rolisteam.qxIDuA:1:1: module "QtQuick" is not installed
15:22:31 - Error - file:///tmp/rolisteam.qxIDuA:3:1: module "QtQuick.Controls" is not installed
15:22:31 - Error - file:///tmp/rolisteam.qxIDuA:2:1: module "QtQuick.Layouts" is not installed
```

**Comment by obiwankennedy** [comment]
Le appimage n'inclut pas certain module qml mais je sais pas pourquoi car je lui dis de le faire.

**Comment by menestrwell** [comment]
oui c'est avec lui que j'ai fait la fiche :)

**Comment by obiwankennedy** [comment]
Est-ce que ce AppImage fonctionne mieux: http://blog.rolisteam.org/file/Rolisteam-1.9.3-v2-x86_64.AppImage

**Comment by menestrwell** [comment]
Beaucoup mieux :)

![image](https://user-images.githubusercontent.com/75116332/102358098-67e7c000-3faf-11eb-98c5-0ac8d7c931e0.png)


Merci

**Comment by obiwankennedy** [comment]
Pourrais-je avoir la version finale de la fiche avec les images, il y a moyen de faire bien mieux maintenant avec la 1.9.3.

**Comment by menestrwell** [comment]
la version partagée dans ce fil est la dernière, seule nuance est l'image embarquée. Voici celle avec l'image

[starwars-1_9-yoda-meme.rcs.zip](https://github.com/Rolisteam/rolisteam/files/5710581/starwars-1_9-yoda-meme.rcs.zip)

**Comment by menestrwell** [comment]
Je pense essayer d'en faire une from scratch lié à Kuro (système de D6 où le 6 est relancé et où le 4 vaut 0, avec des cas où l'on relance le 5, ou encore des bonus aux jets de dés), de beaux algos en somme
