### ISSUE TITLE
Inclure une formule.

### ISSUE THREAD

**Issue by panaore** [Rolisteam/rolisteam#135]
Bonjour. 
Je suis novice en prog.
Je suis en Train de créer une fiche de perso pour Warhammer V4.
J ai inclus des zones de textes pour mettre les caractéristiques.
Je voudrai inclure une cellule oú je peux faire un calcul de plusieurs zones de texte.
Du genre =id9+id10+id11
C est juste un exemple. Je sais qu il y a des symboles a mettre. Mais rien ne y fait. Ça ne marche pas.
=${id_9}+${id_10}+${id_11}
Quand je généré le code pour visualiser la fiche, je n ai rien, pas de fiche de personnage à l affichage.
De plus,cette formule doit se mettre dans quelle colonne ? Dans valeur ? Ou autre ?
Merci de vos réponse.

<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 
Operating System and version (remove irrelevant): 
*  Windows (XP,Vista,7,8,10..)
*  Linux (Ubuntu 16.04, ArchLinux, Redhat)
*  Mac OS X (10.6, 10.7 etc)

Rolisteam Setting (remove irrelevant):  
* GM and Server
* GM and Client 
* Player and Client
* Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-
-
-

#What did you expect to see ? (Make sentences and explains in details with words)
-
-
-

#What did you get instead ? (Describe in details the issue) 
-
-
-

**Comment by obiwankennedy** [comment]
Les formules ne marchent que dans les personnages, si vous essayez de définir des formules dans les données de rcse. Ça ne fait rien. Il faut créer des personnages et éditer les formules dans ces personnages.

Ce comportement va changer dans les prochaines versions.
