### ISSUE TITLE
Rolisteam doesn't play flux

### ISSUE THREAD

**Issue by Yot67** [Rolisteam/rolisteam#16]
Hi,
When I try to stream an online mp3, ogg, Flac ,.. or to play the TabletopAudio's playlist, Rolisteam shows a red "Error" before the http adress.
I'm pretty sur it's not my firewall, other possibilities ?
Thx.

**Comment by obiwankennedy** [comment]
Rolisteam uses your system abality to read remote files. 
So, what is your system ? version ?

**Comment by Yot67** [comment]
windows 7, firefox can play the files

**Comment by obiwankennedy** [comment]
And windows media player ?

**Comment by Yot67** [comment]
Je ne l'ai pas installé sur mon pc.

**Comment by Yot67** [comment]
Okay  ,I've just activated WMP and he can play the streams too

**Comment by obiwankennedy** [comment]
Great!!!

**Comment by Yot67** [comment]
but Rolisteam still can't :(

**Comment by obiwankennedy** [comment]
Can you play local audio file ? from your computer ?

**Comment by Yot67** [comment]
yes and yes

**Comment by obiwankennedy** [comment]
Ok the problem is not about codec and stuff.

**Comment by Yot67** [comment]
my bad, it was my stupid windows firewall

**Comment by obiwankennedy** [comment]
ok! great news!
