### ISSUE TITLE
IPv6 support ?

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#17]
Hi !

Rolisteam does not seem to support IPv6. It should at least display both IPv4 AND IPv6 when available.

Please note that IPv6 does not have any NAT structure, and then should theoretically cause far less connection problems.

Thanks !

**Comment by Blacky---** [comment]
I can join a Rolisteam server with its IPv6. Hosted on Win7, default network stack.

**Comment by obiwankennedy** [comment]
Yes, the ipv6 should work. I can't make a lot of tests here. but Qt5 supports IPv7, so does Rolisteam.

**Comment by sioc-de-narf** [comment]
IPv7 or IPv6 ? your question is titled "IPv6 support ?" ?

**Comment by obiwankennedy** [comment]
oups…

**Comment by obiwankennedy** [comment]
There is some issue to display it. I will fix that but the support it working.
