### ISSUE TITLE
{1 added for each dice rolls output

### ISSUE THREAD

**Issue by Blacky---** [Rolisteam/rolisteam#18]
Win7, Rolisteam 1.7.0:

Chat input: !3d6

Chat output:
Vous avez obtenu 7 à votre lancer de dés [3d6 (2,4,1)] {1

The {1 should not be here :)

**Comment by obiwankennedy** [comment]
it seems to be windows only issue. 
I will check that.

**Comment by obiwankennedy** [comment]
Translation issue.

**Comment by obiwankennedy** [comment]
this file fixes the issue: http://blog.rolisteam.org/file/rolisteam_fr.qm

You may set it as default translation in preferences panel.
