### ISSUE TITLE
Features : Add card deck support

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#19]
Please add creation of custom card decks with an interface to create the deck, card by card and card copy, with selection of same image as front and images for the front.
Ability to show front or back by default on showing the card on the board.
Ability to flip the card on the board.
Ability to script dealing automaticly n cards to a specific player.
And the choice to allow draw by GM only or not.
Choice to count or not cards in user hands.

The lack of such feature is why i am stuck with roll20...

**Comment by Blacky---** [comment]
Could be quite an interesting feature, I see a lot of people on Roll20 or Fantasy Grounds using cards deck for a lot of various things.
