### ISSUE TITLE
Add Feature : post-it

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#20]
Ability to write on the fly on the board or in an object but not in a text box in the toolbar like it is the case currently

**Comment by Blacky---** [comment]
I think he means:

Now to write a text we have to:
1. Write the text in the very very small textfield in the toolbar
2. Select the Text tool
3. Click on a map/image

What would probably be better would be:
1. Select Text tool
2. Click on the map/image
3. See a blinking cursor there
4. Type your text directly unto the image/map

**Comment by obiwankennedy** [comment]
Already done in the vectorial map.
