### ISSUE TITLE
Question : How to roll dices for Cortex+ system

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#21]
see https://en.wikipedia.org/wiki/Cortex_Plus

**Comment by obiwankennedy** [comment]
The main difficulty is to roll several dice (with different number of faces) and do some sorting on it (like the keep operator).

For the moment, it is not possible. 
With the 1.7.1, it will be possible to roll: 1d6;1d4;1d12 for example and get the result properly. 

I may introduce in future version (1.8) the merge operator to create a dice list which gather all previous dice result. So It will be possible to use all other operator on the list.

**Comment by sioc-de-narf** [comment]
Merci pour ce retour. / Thanks for the answer.

**Comment by obiwankennedy** [comment]
Did you try to run dice command with 1.7.1.

**Comment by sioc-de-narf** [comment]
It works. Could it be possible to have the result and detail in reverse order or having a setting to choose ?

**Comment by obiwankennedy** [comment]
not until the merge operator.
