### ISSUE TITLE
Characters portraits & tokens

### ISSUE THREAD

**Issue by Blacky---** [Rolisteam/rolisteam#22]
From issue #8 ; to be more precise for this feature request:
1. Adding a portrait: could be something like right click on a character name (which open a file browser), and a drag&drop an image unto a character name.

1bis. That image is shared with everyone automatically.
1. Portrait appear (after being properly resized) before any text in chat for that character (not the player identity, the PC/NPC identity)
2. Map tokens for these character use the (properly resized) image.

That would not replace the feature request about being able to add "image object" unto another map/image (what issue #8 asks for), because with this way such PC/NPC portraits can have all the token features (state, orientation, name). Both are useful.

**Comment by obiwankennedy** [comment]
already implemented (except for the drag and drop image on character name) in v1.8.

**Comment by sioc-de-narf** [comment]
hello, I dunno I should post a new enhancement request for that...

It would be great to be able to change the image displayed on the token from a given image list per token.

Let me explain : The playe play a werewolf, and he can choose to display his character avatar as human, wolf or hybrid, so we can see in what 'form' his character is currently..

**Comment by Blacky---** [comment]
I second that.

I would also add that such a functionality may be used for other things: illusions, different state of being, maybe even a crude version of a tagging system (wounded, sleeping, paralyzed, etc.)

Could be a simple right click on the token (by the GM or the owner of said token) that display a list with all available alternatives tokens, click on the one you want, and that's it.

**Comment by obiwankennedy** [comment]
For the moment, it is possible (in v1.8) to set an avatar to character and those avatar are used as token on map. 
It is possible to set dynamically the list of state. Each state has picture (and color). When a character is in specular state the picture of the state is showed above the avatar. 
The states are shared with all players. So, it answers not completely our request. For the moment, I will stay like this. In future version, I may add list of picture for character given there state.

**Comment by Blacky---** [comment]
As I understand it, two main things remained for next version:

- having the portrait displayed in chat
- the ability to very quickly change between portraits, and/or pile up images to generate a portrait

**Comment by obiwankennedy** [comment]
Let's create another feature request for that.
