### ISSUE TITLE
Improved readability of token names on map/images

### ISSUE THREAD

**Issue by Blacky---** [Rolisteam/rolisteam#23]
A small but strong shadow (or glow) around the names of tokens would help improve readability, especially for some colors and some type of map background.

I would propose something like a 2px 75% solid (25% transparent) black glow for light colored names, and a 2px 75% solid white glow for dark colored names. 

Or something along those lines.

**Comment by obiwankennedy** [comment]
I think I may propose the ability to set color and background color for text on token.
