### ISSUE TITLE
Feature : Add Fate / Fudge Dices Roll

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#26]
Add the Fate / fudge dice : it's a d6 with 2 faces with 0 (or nothing on physical dice), two faces are + (plus), and two faces are - (minus)

ex of Roll : 
# - 0 + + = +1
# 0 0 - + = 0
# - - 0 + = -1

**Comment by obiwankennedy** [comment]
No need to change, rolisteam can already manage this kind of dice.  You have to add in your preferences (or the preferences of your GM): the following alias:

DF => d[-1-1]

So, your player will just have to call: 4DF

You may also directly call 4d[-1-1]. It is the same. 
It will roll 4 values between -1, 0 or 1.
