### ISSUE TITLE
NPC state configuration

### ISSUE THREAD

**Issue by Nicoloye** [Rolisteam/rolisteam#27]
Hello, I couldn't find a similar request, sorry if it is a duplicate.

First of all thanks for the great software, you guys rock !

Here are two feature suggestions, I hope they can help improve the UX for the community.

I think being able to set the token states and color could be pretty cool as the default states may not fit every game or may be too restrictive. For example if I want to play "Mouse Guard" there are states like "Starving", "Angry", "Tired" or "Ill" that are needed. Even basic games like Dungeon and Dragons may need things like "Stunned", "Tied", etc.

With the same logic some combat status may be handy (for example a little icon on the lower corner of a token) for things like "On the defensive", "Hidden", "Charging", etc.

The second feature is maybe too complex, but I think the first one is a must to have :)

**Comment by obiwankennedy** [comment]
It should not be difficult to make. But I will implement it only in vectorial map. It will  be part of ruleset and I hope to make it available in v1.8.
