### ISSUE TITLE
hide Roll Dice from the roller

### ISSUE THREAD

**Issue by obiwankennedy** [Rolisteam/rolisteam#28]
Roll dice and show the result only to the GM.

**Comment by Blacky---** [comment]
I don't understand this need. Why the GM doesn't roll by himself???

**Comment by obiwankennedy** [comment]
Because perhaps, he or she does not want to be bored by this kind of stuff. If he/she asks to all his/her players to do an unveil perception roll, it faster when every players make it on their own.

Some other software provides this, It was required by some of rolisteam user.

**Comment by obiwankennedy** [comment]
Your dice command should start with # to use this feature. 
example: #2D6
