### ISSUE TITLE
It is not possible to move sheets around as if on a regular table

### ISSUE THREAD

**Issue by Whidou** [Rolisteam/rolisteam#3]
This feature request was prompted by the following discussion: http://lesateliersimaginaires.com/forum/viewtopic.php?f=73&t=3495#p31609 (fr).

Some games such as [_Fiasco_](http://www.bullypulpitgames.com/games/fiasco/) or [_L'Agence_](http://lesateliersimaginaires.com/forum/librairie#agence) require moving post-it notes around the gaming area. As of [1.6.1](https://github.com/Rolisteam/rolisteam/tree/1.6.1), this cannot be reproduced in Rolisteam, preventing these games from being played easily.

This feature could be achieved by adding a new document type in addition to _Map_ and _Image_ that would enable the creation and edition of opaque text areas. A _Diagram_ or _Vector drawing_ document type would fit the bill.

Thank you for your consideration.

**Comment by obiwankennedy** [comment]
I'm thinking to implement it in maps. The new version of map in rolisteam will be vectorial, so it will be possible to draw rectangle as post-it, add text item, and then link the post-it and the text to attached the text on the post-it. It should do the trick.

**Comment by obiwankennedy** [comment]
The work on vmap are stating to pay: I think It is closed of what you want. 
![rolisteam_issue_ 3](https://cloud.githubusercontent.com/assets/69177/10438113/ed51fd98-7131-11e5-996e-598671251947.png)


For a small video: http://blog.rolisteam.org/file/rolisteam_issue_3.mp4
