### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by KonalaAK** [Rolisteam/rolisteam#33]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)
# Your configuration:

Rolisteam version: v1.7.1
Operating System and version: 
- Windows 10

Rolisteam Setting: 
- Player and Client
# What did you do ?
- I connect without any problem
- After 5 minutes I am disconnected and If I reconnect my character exist in double
# What did you expect to see ?
- I expect to stay connected

**Comment by obiwankennedy** [comment]
Hi, 

This kind of behaviour is often caused by Anti-virus/firewall softwares which cut off the connection.
Please check if any software like that may run on your computer. Then you may take a look to the settings of those software.

Renaud

**Comment by obiwankennedy** [comment]
Hi, 
Could you tell me if when it is closed you haven't send anything on the network.

To be clear, I'm getting suspicious about a protection mechanism with close the connection if it was not been used for a while. If you send a text message (for example) every minutes does it help or not ? I may introduce mechanism to send heartbeat message to prevent that to happen.

Let me know if it is help.

**Comment by Esgorhannoth** [comment]
Hi,
I have this kind of problem too. For me, disconnects mostly happen when the client is not in use for some time (i.e. no messages sent or received).

**Comment by obiwankennedy** [comment]
Ok, I will implement the heartbeat mechanism, hoping that solve the issue.

**Comment by Esgorhannoth** [comment]
Playtested 7286017 commit today for about 3 hours. There was only one disconnect with further client segfault crash, otherwise the connection was pretty stable. Though I like the idea of heartbeat messages.

**Comment by obiwankennedy** [comment]
Yes, if you are using dev version it may include some issue. I'm currently working on heartbeat and improving the vectorial map system. To make it usable and stable. If you notice anything, please let me know. It will be really helpful.

**Comment by obiwankennedy** [comment]
Heartbeat feature must do the job in v1.8
