### ISSUE TITLE
Error: Compile error in Ubuntu 15.10,old packages qt5 replaced in the current version of ubuntu

### ISSUE THREAD

**Issue by luizrpgluiz** [Rolisteam/rolisteam#34]
Hello developer, there was a substitution of names in the current version of qt5 in ubuntu, the error has is that the time to download the libqt5-core packages, libqt5-gui and libqt5-dev, in the Ubuntu repositories, their names have been changed, please check out the new repository names and update the wiki to build the rolisteam site.

**Comment by obiwankennedy** [comment]
The documentation has been amended.
Thanks!
