### ISSUE TITLE
Bug: can't select Unveil/Hide in palette box

### ISSUE THREAD

**Issue by Vladar4** [Rolisteam/rolisteam#36]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0 (master branch @ 2016.05.24)
Operating System and version: 
- ArchLinux (4.5.4-1-ARCH)

Rolisteam Setting: 
-GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Create game host
- File → Open → Map
- Select jpg image
- Check "Hidden" check-box
- Click "OK"

#What did you expect to see ? (Make sentences and explains in details with words)
- To be able unveil/hide regions of the map

#What did you get instead ? (Describe in details the issue) 
- Unveil/hide boxes in palette toolbox are disabled, can't select them

**Comment by obiwankennedy** [comment]
I will check on that in the current week.

**Comment by obiwankennedy** [comment]
it should be fixed. I let you close the bug if the patch resolves the issue.

**Comment by Vladar4** [comment]
Fixed by 7bf6c05d85c4e9306f261a0a21c48ec2187dd130
