### ISSUE TITLE
Bug: Player can see hidden areas of the map

### ISSUE THREAD

**Issue by Vladar4** [Rolisteam/rolisteam#38]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0 (master branch @ 2016.05.26)
Operating System and version: ArchLinux (4.5.4-1-ARCH)

Rolisteam Setting: 
-GM and Server / Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
- As GM:
    - Create game host
    - File → Open → Map
    - Select jpg image
    - Check "Hidden" check-box
    - Click "OK"

- As player:
    - Connect to the created game

#What did you expect to see ? (Make sentences and explains in details with words)
- Player shouldn't see hidden areas of the map

#What did you get instead ? (Describe in details the issue) 
- Player can see hidden areas of the map as GM (on any level of opacity set by GM)

**Comment by obiwankennedy** [comment]
I will check that tonight.

**Comment by obiwankennedy** [comment]
I commit some stuff to fix this issue. I recommend you to update your clone.

**Comment by Vladar4** [comment]
Fixed by d3eb9249d08b7136e9e7c13729b7389fc539f49b
