### ISSUE TITLE
But: Can't load Scenario

### ISSUE THREAD

**Issue by Vladar4** [Rolisteam/rolisteam#40]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: Rolisteam version: 1.8.0 (master branch @ 2016.05.27)
Operating System and version: ArchLinux (4.5.4-1-ARCH)

Rolisteam Setting: 
- GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Create game host
- File → Open → Map
- Select jpg image
- Click "Ok"
- File → Save into Scenario
- [Optional: Restart program (same result)]
- File → Open → Scenario

#What did you expect to see ? (Make sentences and explains in details with words)
- Loaded map

#What did you get instead ? (Describe in details the issue) 
- Loading error: "Unsupported file format"
- If then click on map file in Resource Explorer — same error.

**Comment by Vladar4** [comment]
Shouldn't unveiled regions and PC-markers on the map save into Scenario too?

**Comment by obiwankennedy** [comment]
I invite you to update the code I've added some changes that should fix that.
I can save map into scenario and reload it, the visible region are as before saving.

**Comment by Vladar4** [comment]
Thanks, it working now.
