### ISSUE TITLE
Mix between GM and player rights

### ISSUE THREAD

**Issue by Alkor1** [Rolisteam/rolisteam#41]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)
# Your configuration:

Rolisteam version: 1.7.1
Operating System and version: Windows 10

Rolisteam Setting: 
-Player and Client / Player and Server
# What did you do ? (Explain each step from starting rolisteam to the issue)

-Connected to the system with "Ask to be GM" checked while a GM was already logged in.
# What did you expect to see ? (Make sentences and explains in details with words)

-the **regular player** interface, since there was already a GM logged in.
# What did you get instead ? (Describe in details the issue)

-Almost all the the GM abilties, including moving everything around even even with restricted rights, the GM music controls, ability to edit the fog of war and see through it (in purple on the picture).
-The part to resize the NPCs is missing, but I can can still create and remove them.
![sans titre](https://cloud.githubusercontent.com/assets/19768106/15810447/f958246e-2b9e-11e6-83b6-c580df3a9bcf.jpg)

**Comment by obiwankennedy** [comment]
I will take a look at that. It will be fixed into v1.8.0
