### ISSUE TITLE
How to auto-size Huge map

### ISSUE THREAD

**Issue by bbassac** [Rolisteam/rolisteam#42]
Hi, our GM draws very detailled maps and scan them.
When openning in Rollisteam, we always need to scroll a lot, and resize many times the windows to fit the map in the screen.

Is there an auto-resize map Function or is it possible to create it ?

Thanks

**Comment by obiwankennedy** [comment]
Ok, it can be manageable. 
Just to be clear, the only the size of the map window will change. Managing Zoom level in old map system is very difficult due to the complexity of current map system.

**Comment by bbassac** [comment]
Hi. Thank you for your response but i don't understand it (i 'm french).
When our GM display for us a Picture (a map), me need to reduce the size of the window many time.
Is it possible to add a "Zoom in / Zoom out (with Ctrl + clic for example) ?

Obviously , the size on PC and NPC wust stay visible.

Do you think it's possible ? (i could her you, but i m only Java developper)

**Comment by obiwankennedy** [comment]
Tu peux parler français dans ce cas. :-)

En faite, j'ai déjà essayé de mettre une gestion de zoom sur les plans, cela fout un gros désordre car le système de coordonnées ne marche pas bien après. Cela rend la chose assez inutilisable.
Cependant, la version 1.8 arrivent avec un nouveau système de plan qui lui gère très bien le zoom. 

Je peux faire en sorte que la fenetre ait la taille de l'espace de travail mais ajouter du zoom, c'est trop compliqué. Le code des vieux plans est très complexes. J'ai pas envie de perdre trop de temps la dessus.
Dans l'absolue c'est possible mais c'est long. Il vaut mieux que je me concentre sur la sortie des plans vectoriel.

**Comment by obiwankennedy** [comment]
V1.8 fixes the issue.

**Comment by bbassac** [comment]
Waou !
Franchement, bravo pour cette version. Hate de la tester ce week end.

Clap clap

ps : d'un dev à un autre : ta changelog est impressionante, mais des
versions plus petites avec des intervals plus court, c'est bien aussi ^^

Merci pour tout !

Bruno

2017-02-19 20:28 GMT+01:00 Renaud G. <notifications@github.com>:

**Comment by obiwankennedy** [comment]
Certes, mais pour les versions majeures je table sur l'ajout d'une ou deux grosses fonctionnalités, tant que c'est pas fait je ne sors pas la version. La v1.9 ne sortira pas tant que le serveur stand alone ne sera pas prêt. etc..
