### ISSUE TITLE
Bug: Can't see each others PCs

### ISSUE THREAD

**Issue by Vladar4** [Rolisteam/rolisteam#43]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0 (master branch @ 2016.07.13)
Operating System and version: ArchLinux (4.6.3-1-ARCH)

Rolisteam Setting: 
-GM and Server / Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Create game as DM
- Connect to the game as Player
- As DM: File → Open → Map and load map
- Add PCs as DM and as Player

#What did you expect to see ? (Make sentences and explains in details with words)
- DM and Player should see each others PCs

#What did you get instead ? (Describe in details the issue) 
- DM can't see Player's PC
- Player can't see DM's PC
- Console outputs a bunch of:

"PC ID not found (showPc - map.cpp)"

"PC ID: %1 not found (isVisiblePc - map.cpp)" {cdd3e9c8-9472-4dda-b7ca-455c587f3d85}

**Comment by obiwankennedy** [comment]
I think this kind of problem occurs while people try to connect when the server is not on. 
That leads to add some PC id which mess around a bit.

**Comment by obiwankennedy** [comment]
Let me know if the fix does the trick.

**Comment by Vladar4** [comment]
It works great except for one instance:

If DM opens map **before** player is connected, then Player's PC (that created automatically) is not seen by DM if placed on map.

Errors on DM's side: "PC ID not found (showPc - map.cpp)"

When Player creates and places on map another PC, DM can see it.
