### ISSUE TITLE
Bug: Segfault when somebody quits

### ISSUE THREAD

**Issue by Vladar4** [Rolisteam/rolisteam#44]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0 (master branch @ 2016.07.13 commit 70229760789788222762c5dd6b2fa82e99b2cf62)
Operating System and version: ArchLinux (4.6.3-1-ARCH)

Rolisteam Setting:
-GM and Server / Player and Client

Rolisteam Setting: 
- Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Create game as DM
- Connect to the game as Player (or several players)
- Quit as Player

#What did you expect to see ? (Make sentences and explains in details with words)
- Player quit normally

#What did you get instead ? (Describe in details the issue) 
- All other working instances instantly crash with segfault

**Comment by obiwankennedy** [comment]
It should fix the issue.

**Comment by Vladar4** [comment]
Fixed
