### ISSUE TITLE
Feature: Player/GM shared notes board

### ISSUE THREAD

**Issue by Esgorhannoth** [Rolisteam/rolisteam#45]
It would be a good feature to add a simple text area window with Lock/Unlock button for taking notes that can be viewed and edited by both player and GM. It could be useful in multiple cases like:
- player character sheet (text only)
- tracking experience, health, money etc
- tracking any kind of tokens or points for various game systems
- even ASCII-art maps :) Though it would require a monospace font

Example use session would be like:
1. Player locks the text area window for herself with Lock button so that GM could not edit it
2. Player writes or updates something in the area
3. Player unlocks the area with Unlock button, so that it could be used by anyone (player or GM) again
4. GM wants to add some note for player, or make a correction
5. GM locks the board with Lock button, so that player could not edit it
6. GM writes note or makes corrections
7. GM unlocks the board with Unlock button so that it is usable for anyone again.

**Comment by obiwankennedy** [comment]
I plan to include  shared note as new media into rolisteam. 
The composant already exists: https://github.com/obiwankennedy/cahootseditor .
It is a free software and I will include into rolisteam after the release of 1.8.

**Comment by obiwankennedy** [comment]
The integration of the software is now done in the development branch of rolisteam project. It will be available with Rolisteam 1.9. 

The lock/unlock system is not working as you describe. The software provides a better way to integrate changes from several person. I hope it will fit all you wishes.
