### ISSUE TITLE
Mingw49_32 compilation error (w/ possible solution)

### ISSUE THREAD

**Issue by Esgorhannoth** [Rolisteam/rolisteam#47]
Hi,
I have Windows 7 Home Basic 32-bit and build Rolisteam with Qt Creator (community) via Mingw-g++.

For some time I could not build Rolisteam with the same strange error aborting compilation:
```
src/network/networkmanager.h:56:70: error: expected identifier before numeric constant
    enum ConnectionState {DISCONNECTED,CONNECTING,LISTENING,CONNECTED,ERROR};
                                                                      ^
src/network/networkmanager.h:56:70: error: expected '}' before numeric constant
src/network/networkmanager.h:56:70: error: expected unqualified-id before numeric constant
```
.... and screenful of others.

It turned out that mingw defines ERROR in file 
```
Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/wingdi.h
```
on line 66:
```
#define ERROR 0
```
which prevents bin/chatlist.o from building.

I propose adding in src/network/networkmanager.h before ```class Player;``` these lines:
```
#ifdef ERROR
#undef ERROR
#endif
```

With these lines Rolisteam builds just fine.

**Comment by obiwankennedy** [comment]
I just remove error, it is not used in fact.
