### ISSUE TITLE
Typo Visinneur de fiche de personnage

### ISSUE THREAD

**Issue by Blacky---** [Rolisteam/rolisteam#49]
Dans 1.8.0, typo : il est écrit «Visinneur de fiche de personnage» au lieu je suppose de Visionneur. Qui n'est pas vraiment français non plus ;) Afficheur serait mieux je pense, ou alors Vision de, ou Affichage de.

**Comment by Blacky---** [comment]
Je ne vais pas ouvrir un ticket pour ça, mais dans les Préférences il y a un onglet nommé _Les régles_. Les règles plutôt non ? Bien que ça ne soit pas très parlant.

Moi je mettrais : 
- 3e onglet : Chemins de fichiers
- 4e onglets : Outils & règles

**Comment by Blacky---** [comment]
Argh erreur de ma part, je ne voulais pas fermer le ticket.

**Comment by obiwankennedy** [comment]
Ok, des problèmes avec la traduction française. C'est noté. C'est pas le plus complexe. hihi!
