### ISSUE TITLE
Building from git clone not straightforward

### ISSUE THREAD

**Issue by jcelerier** [Rolisteam/rolisteam#5]
Hello,

I think that the docs should mention that there is a submodule to update if one wants to build from source.

Also, the submodule seems to be registered weirdly : 

    $ git submodule update --init 
    	Sous-module 'src/dicepraser' (git@github.com:obiwankennedy/DiceParser.git) enregistré pour le chemin 'src/diceparser'
	Clonage dans 'src/diceparser'...
	The authenticity of host 'github.com (192.30.252.130)' can't be established.
	RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
	Are you sure you want to continue connecting (yes/no)? yes
	Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
	Permission denied (publickey).
	fatal: Could not read from remote repository.

And seems to have a typo (src/dicepraser). 

Thank you very much ! (also, the build worked out of the box with Qt 5.4, which is very nice :p)

**Comment by obiwankennedy** [comment]
Yes, that right, I did not well describe the compilation process from git.

**Comment by obiwankennedy** [comment]
-Spelling & documentation have been updated.
http://wiki.rolisteam.org/index.php/CompilationLinux

I close the ticket.
