### ISSUE TITLE
Convertisseur d'unité ne fonctionne pas ou mal

### ISSUE THREAD

**Issue by Blacky---** [Rolisteam/rolisteam#51]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0
Operating System and version: 
- Windows 10 

Rolisteam Setting: 
GM & Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Launched Rolisteam as a GM
- Menu Boîte à outils du MJ, Convertisseur d'unités
- Click on things

#What did you expect to see ? (Make sentences and explains in details with words)
- Things. That did not happened :) 

#What did you get instead ? (Describe in details the issue) 
Ok, some specifics:
- Click on the … button. Nothing happens.
- Click on the left Select button.  Nothing happens.
- Click on the right Select button.  Nothing happens.
- Input a number (5) on the left Textarea. Then click on the Select button. Nothing happens.
- Select Distance, then Select back temperature. Now the Convertir Select button has values in it. Click on farenheight. Still has 5 typed below it. Select kelvin on the right.  Nothing happens.
- Select Monnaie. Only 3 types of money appear. I was expecting, well, a little more. At least USD, €, British pounds, Japan Yen, etc.
- Select Volume. No type to select from. At all.

**Comment by obiwankennedy** [comment]
For the moment, there are few kind of unit. In the v1.9, I plan to offer the ability to the user to set his own conversion rules. 

The computation is made after changing the value. I will check that. It is not really a blocking thing.

Thanks for you feedbacks.

**Comment by obiwankennedy** [comment]
some improvements has been done in 1.8.1.
I close this bug as we have a ticket to improve it in 1.9.
