### ISSUE TITLE
Mutually anchoring two objects crashes Rolisteam

### ISSUE THREAD

**Issue by MrPus** [Rolisteam/rolisteam#53]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

Rolisteam version: 1.8.0
Operating System and version: 
-Windows 7

Rolisteam Setting: 
-GM and Server / Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-Open vectorial map
-Create two objects A and B
-Anchor object A to object B
-Anchor object B to object A

#What did you expect to see ? (Make sentences and explains in details with words)
-It was not intentional. I did not really expect anything.

#What did you get instead ? (Describe in details the issue) 
-Rolisteam freezes and crashes.

**Comment by obiwankennedy** [comment]
Effectively,  this use case has not been tested.  I Will protect that to happen,  it Will be available on the v1.8.1
