### ISSUE TITLE
Circular field of view is not centered on the character

### ISSUE THREAD

**Issue by MrPus** [Rolisteam/rolisteam#54]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

Rolisteam version: 1.8.0
Operating System and version: 
-Windows 7

Rolisteam Setting: 
-GM and Server / Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
-Activate a character's field of view and chose circular

#What did you expect to see ?
-I expected the field of view to be centered on the character.

#What did you get instead ?
-The further the character is from the top left corner the further the field of view moves away from the character.

**Comment by obiwankennedy** [comment]
You can make circular field of view by using the conical one with the angle set at the max value.
