### ISSUE TITLE
Getting source code is too hard

### ISSUE THREAD

**Issue by SnarkBoojum** [Rolisteam/rolisteam#57]
Hi,

I wanted to give rolisteam a try and decided to start from git sources, but that didn't work : for each and every submodule, I get permission denied errors.

So I started from each such error and cloned by hand : ok.

The impression I have is that it tried to clone with high credentials instead of just trying to clone : it did list the correct repositories and the correct directory names.

If I get the .tar.gz from a release, the sources are incomplete too : it lacks all subrepositories.

Could it be a configuration issue?

**Comment by obiwankennedy** [comment]
Submodules are linked to Rolisteam using git path.  It means that git use the git over ssh protocol to get them.  The solution is to change those links to https.  Then it will work for anyone.  

For the tarball,  it should have the full source code.  I will check that
