### ISSUE TITLE
Images added on a vector plan don't display on the players screen

### ISSUE THREAD

**Issue by HarvoireSamuel** [Rolisteam/rolisteam#59]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version:  1.8.0
Operating System and version: Windows 10

Rolisteam Setting: 
-GM and Server / Player and Client  

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Host Rolisteam
- Ask one of my players to connect to Rolisteam
- Create a Vector Plan
- Add Characters to the vector plan and draw on it
- Right click -> Add an image.
- Set layout to "character", view on "show all" and permissions on "All"

#What did you expect to see ? (Make sentences and explains in details with words)
- That the image I added display in my players screen on the plan

#What did you get instead ? (Describe in details the issue) 
- Even if I move, change permissions/view etc. of the image I added, the player won't see it on his screen.

**Comment by obiwankennedy** [comment]
Try to drag and drop images into the map.  Using the menu approach may cause the problem.

**Comment by HarvoireSamuel** [comment]
It seems to solve the problem ! I'll try more for the days to come but thanks for the quick answer !

**Comment by obiwankennedy** [comment]
I fixed the issue, the fix will be available into v1.8.0

**Comment by HarvoireSamuel** [comment]
Just a thing, now that we try drag'n drop we have two new problems :

1.  When i try to add a new image and turn in into a token, it crashes rolisteam.

2. When we reconnect, the token have a black image for the player (1st image : DM view, 2nd image, player view)

(Do you want me to create another issue about it or we treat it there ?)

![cote joueur](https://cloud.githubusercontent.com/assets/9363228/23321440/d76beb9a-fadf-11e6-81c0-8c3b7a7ff4f4.png)
![cote mj](https://cloud.githubusercontent.com/assets/9363228/23321441/d76ef5b0-fadf-11e6-8a01-e53717beae7d.png)

**Comment by obiwankennedy** [comment]
Players crashes ? but the GM is stil alive ? right ?

**Comment by HarvoireSamuel** [comment]
Yes ! I tried to connect with another Rolisteam on local (127.0.0.1) and expermimented the same thing

**Comment by obiwankennedy** [comment]
fixed in 1.8.1, please open new issue if you experience some trouble.
