### ISSUE TITLE
Rolisteam 1.8.0 don't compile on some Linux distro (QOpenGLWidget only in QT 5.4)

### ISSUE THREAD

**Issue by jlm-gh** [Rolisteam/rolisteam#60]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.0
Operating System and version: Linux Debian Jessie 8 AMD64

Rolisteam Setting: 
Rolisteam 1.8.0 and rcse 1.0.0 won't compile due to QOpenGLWidget present on QT since 5.4

# Rolisteam 1.8.0

```
src/vmap/rgraphicsview.cpp:23:25: fatal error: QOpenGLWidget: No such file or
directory
 #include <QOpenGLWidget>
                         ^
compilation terminated.
Makefile:2601: recipe for target 'bin/rgraphicsview.o' failed
make: *** [bin/rgraphicsview.o] Error 1
```

# Rcse 1.0.0

```
mainwindow.cpp:29:25: fatal error: QOpenGLWidget: No such file or directory
 #include <QOpenGLWidget>
                         ^
compilation terminated.
Makefile:742: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
```
Linux Debian Jessie 8 is using qt5-default 5.3.2+dfsg-4+deb8u2. I guess Ubuntu 14.04 LTS as the same problem as it use an older qt5 (5.2.1+dfsg-1ubuntu14.3)

References:
QOpenGLWidget Class : http://doc.qt.io/qt-5/qopenglwidget.html
Debian 8 qt5-default : https://packages.debian.org/jessie/qt5-default
Ubuntu 14.04 qt5-default : http://packages.ubuntu.com/trusty/qt5-default

**Comment by obiwankennedy** [comment]
It is easy to fix the issue: Change QOpenGLWidget with QGLWidget.

As requirement, Qt5.6 is the default requirement for Rolisteam 1.8
