### ISSUE TITLE
rcse multiple page problem

### ISSUE THREAD

**Issue by Gaynor788** [Rolisteam/rolisteam#61]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.1
Operating System and version: 
win 10
Rolisteam Setting: 
-GM 
#What did you do ? (Explain each step from starting rolisteam to the issue)
- i created two pages.

-
-

#What did you expect to see ? (Make sentences and explains in details with words)
- i wanted the field placed on page 1 to appear where placed on page 1
- i wanted the field placed on page 2 to appear where placed on page 2
-

#What did you get instead ? (Describe in details the issue) 
-when I generate code, all the fields appear onn page one, both in rcse and on rolisteam 1.8.1

-
-

**Comment by obiwankennedy** [comment]
Ok, to fix it in your generated code is easy:
You should have some line like this:
visible: root.page == 0? true : false

You should replace the 0 by the number of the page you want.
I prepare the fix, for the version next version. 
0 => first page
1=> second page 
…

This commit fixes the issue: https://github.com/Rolisteam/rcse/commit/bbce610af6d3192cd0a15ef5f9d0b49f2b2c6dc0

**Comment by Gaynor788** [comment]
thank you

**Comment by obiwankennedy** [comment]
Have you test the v1.8.2 ? If it is fixed. Please close the issue.

**Comment by obiwankennedy** [comment]
Please try rcse v1.0.3, you can download it from http://www.rolisteam.org/download.html

If you are on windows, you just have to download and reinstall rolisteam.

Then, let me know if it fixes the issue.
