### ISSUE TITLE
Character sheets share with eveyone.

### ISSUE THREAD

**Issue by Alkor1** [Rolisteam/rolisteam#62]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.1
Operating System and version: 
-Windows 10

Rolisteam Setting: 
-Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-Started the server (as player)
-Waited until every other player and GM were connected
-The GM shared the character sheets (saved on his own computer)
-Every player recieved every character sheet sent by the GM

#What did you expect to see ? (Make sentences and explains in details with words)
-I expected to only recieve my own sheet while other players recieved only theirs.

#What did you get instead ? (Describe in details the issue) 
-Everyone got every character sheet sent by the GM.

**Comment by obiwankennedy** [comment]
Ok, I fix it and during that I notice that something was off about the stop sharing the character sheet. I will do more tests, then I have to fix another bug inside RCSE and I will release a new version with all recent correction.
