### ISSUE TITLE
Mauvaise gestion de la largeur de la toolbox VMAP

### ISSUE THREAD

**Issue by pit-le-rouge** [Rolisteam/rolisteam#63]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version: Mac OS X 10.12.5
-[ Windows [XP,Vista,7,8,10..] / Linux (Ubuntu 16.04, ArchLinux, Redhat) / Mac OS X (10.6, 10.7 etc) ]

Rolisteam Setting: 
-GM and Server / GM and Client / Player and Client / Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-Je crée une nouvelle VMAP
-La toolbox de la VMAP apparait à gauche
-je change la taille de la toolbox (je réduis sa largeur)

#What did you expect to see ? (Make sentences and explains in details with words)
- une toolbox correctement réargentée comme c'est le cas pour toolbox de la Map "bitmap" qui ne pose aucun problème
-
-

#What did you get instead ? (Describe in details the issue)

- Au lieu de rétrécir l'espace entre les icônes, ces dernières sont très vites affichées sur une seule colonne et certaines icônes se superposent à d'autres, rendant la toolbox inutilisable. Il faudrait commencer par réduire l'espace entre icône avant de tout mettre sur une seule colonne, cela ferait déjà gagner pas mal de place pour cette toolbox qui est très large sur Mac en tous cas. La toolbox de la Map "Bitmat" fait cela très bien , pas de raison que celle de la vampa ne soit pas capable d'en faire autant :-)
-
-

**Comment by obiwankennedy** [comment]
Puis-je connaitre ta résolution d’écran ?

**Comment by pit-le-rouge** [comment]
1440 x 900
c'est sur un MacBook Air

Pit
