### ISSUE TITLE
Renaming notes ?

### ISSUE THREAD

**Issue by m-irigoyen** [Rolisteam/rolisteam#65]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version: 
-Windows 10

Rolisteam Setting: 
- Unconnected

Is it possible to rename notes ? Every created or opened note is named "untitled.txt" in the resource explorer, this makes organizing stuff pretty hard.

**Comment by obiwankennedy** [comment]
Did you try to save them in files ? When you save on disk your notes it will set the title. 
You may need to load the saved file then to get the right name. Of course, 1.9 will provide way to rename any resource.

**Comment by m-irigoyen** [comment]
Saving the note does change the editor window's title, but not the name in the resource explorer.
Opening a note is the same (both html / odt) : correct window title, "untitled.txt" in the resource explorer.
