### ISSUE TITLE
INFO:FFJDR may help with money

### ISSUE THREAD

**Issue by bmorel** [Rolisteam/rolisteam#68]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 
Operating System and version: 
-[ Windows [XP,Vista,7,8,10..] / Linux (Ubuntu 16.04, ArchLinux, Redhat) / Mac OS X (10.6, 10.7 etc) ]

Rolisteam Setting: 
-GM and Server / GM and Client / Player and Client / Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-
-
-

#What did you expect to see ? (Make sentences and explains in details with words)
-
-
-

#What did you get instead ? (Describe in details the issue) 
-
-
-

**Comment by bmorel** [comment]
i hate that phone... can't even clear an issue ´s area.
Ok i simply wanted to point out that the Federation Francaise du Jeu De Role (ffjdr for search engines, french website) offers to support by money projects to promote RPGs, and I thought that someone could eventually take advantzge of that to improve rolistik... sorry, rolisteam ;)
Just in case. I'm not affiliated with those guys in any way, i simply just tried to get back into tabletop rpg around my new location and thought someone could be interested by info in that good old soft one resurected 6-7 years ago and that's still alive. goals are same after all.

**Comment by obiwankennedy** [comment]
Do you have some link about this project ?
