### ISSUE TITLE
Playing sounds randomly works

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#7]
Hi,

We experienced several issues with playing sounds for our game session.

Here is the context, along with the issues encountered (version 1.6.1) :

- C1 (GM) : Linux Debian 8, binaries compiled on Debian 7 / can add musics to the playlist (not loaded automatically from GM musics directory though, don't know if it's a feature or a bug) and play them with no problem
- C2 (player) : Windows 7  / can play one music on GM command, but does not change the track afterwards
- C3 (player) : Linux Ubuntu 15.04 / can play musics only after playing one of them in an external (not rolisteam) player (totem)
- C4 (player) : Windows 7 / can play musics on GM command with no problem
- C5 (player) : Windows 7 / cannot play any music (tried everything, including copy/pasta from the config of C2)

Everyone unzipped the exactly same archive into the directory configured in "musics directory (player)" parameter.

Tried to close/open rolisteam with no relevant results. Parameters seem OK for everyone.

Furthermore, C2, C3, C4 and C5 had the message "unable to open or corrupted file..." each time the GM changed the track. However, the sound played correctly for C2, C3 and C4 despite this warning.

However, i think C5 might be in version 1.6.2 (to be confirmed).

Thanks for your support and the great work otherwise :)

**Comment by obiwankennedy** [comment]
Ok, thanks for the feedbacks. The sound system has been totally reviewed and reworked in the next release of rolisteam (v1.7). So, my quick answer is: wait for the new version (should be in fews days), then test again playing music. It should fix many issues.

Last thing, v1.6.2 does not exist.

**Comment by superllm** [comment]
:+1: 

So, wait and see. Fine for me.

My bad for v1.6.2, i checked when he said it to me and didn't find any but i thought it may be a "quick fix" version proposed only for Windows.

**Comment by superllm** [comment]
So far so good, the sounds player works like a charm. I have to check it with all my players though.

**Comment by obiwankennedy** [comment]
Good news!

**Comment by obiwankennedy** [comment]
May I close this issue ?

**Comment by superllm** [comment]
Seems to work in 1.7.1. Thanks ! :)
