### ISSUE TITLE
Feature: demande de fonctionnalité au feuille de personnage

### ISSUE THREAD

**Issue by demonskill** [Rolisteam/rolisteam#70]
Je trouve qu'il manque quelque fonctionnalités au créateur de feuille de perso : 
- pouvoir exporter les différentes fiches de personnage en .png ou .pdf
- pouvoir assigné des formules dans les valeurs des entré texte qui puissent s'appliquer à tout les personnages crées sans avoir à retaper les formules pour chaque personnage.
- le support du ctrl+z

**Comment by obiwankennedy** [comment]
Ce ticket est pour RCSE et non pour rolisteam. Je le déplace ici: https://github.com/Rolisteam/rcse/issues/6
