### ISSUE TITLE
UI bug when receiving character sheet

### ISSUE THREAD

**Issue by flavienaudin** [Rolisteam/rolisteam#71]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version: 
-Windows 10

Rolisteam Setting: 
- Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Join a party 
- The GM send me a character sheet and the interface bug : the top menubar (Fichier, Fenêtres....) disapears.

#What did you expect to see ? (Make sentences and explains in details with words)
- A new subwindow with the character sheet and the interface still working
-
-

#What did you get instead ? (Describe in details the issue) 
- the new subwindow is opened but with the top title area not responsive to click (move the window, close...)
- The tile area of every sub-windows is disabled : nothing appends when clicking : reduce, move, close.
- The left toolbar and the right menus (notification area, chat...) are partially hidden = outside the main frame.

The same bug occurred to another friend

**Comment by obiwankennedy** [comment]
You and your friend, do you have anything installed on windows ? such as Fancy wallpaper, theme, same graphic card ? some software with an impact on visual aspect of windows ? 

As it does not occurs on every windows 10, I recommended to disable one by one each component with visual impact and to test rolisteam.

**Comment by flavienaudin** [comment]
The first evening we played, only my friend got the bug, the second play, we both got the bug.
I don't have any Fancy wallpaper, neither theme. 
We have the same PC (portable Dell XPS15)  so the same graphic card, with 4K screen and a non-4K second screen.
No software to modify windows aspect.

I'm going to do some tests by disabling screens and some components (I don't know which ones) and give you feedback.

**Comment by obiwankennedy** [comment]
There are some bugs related to your computer on Qt bug trackers:

https://bugreports.qt.io/browse/QTBUG-62127 and few others.

**Comment by obiwankennedy** [comment]
Any news ? Did you install new driver for you graphic card ?

**Comment by flavienaudin** [comment]
Hi, 
I can't update my graphic card driver because Dell didn't verify driver yet. I tried installing previous version of the driver and it works well. So I'm waiting for the new driver from Dell and then I will tell you if the bug is fixed, but I'm quite sure it will be OK

Thank for your investigation.
