### ISSUE TITLE
QNetworkAccessManager causes latency on Wifi connection for Windows.

### ISSUE THREAD

**Issue by Torbaal** [Rolisteam/rolisteam#72]
[![Build Status](http://www.rolisteam.org/sites/default/files/pixture_reloaded_logo.png)](http://www.rolisteam.org)

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version: 
-Windows 7

Rolisteam Setting: 
-Player and Client

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Each time I start Rolisteam, my connection to Team Speak drops so much I'm barely able to communicate with my fellow players and DM.
- TS ping goes from 24ms to 300+

#What did you expect to see ? (Make sentences and explains in details with words)
- Being able to use Rolisteam and TS at the same time without any issue

**Comment by obiwankennedy** [comment]
1/ Which kind of Internet connection do you have ? Can you check on windows the usage of network?

2/ When you reach the server, the server sends you many data (such as  character avatar). If there is a lot of thing to load. It may take sometime and damage a bit you connection. But when it's over everything should be fine.
At the connection, be sure to have the notification zone visible. It shows a progress bar when rolisteam is receiving a large amount of data from the network. 

3/ Have you activate the heartbeat message ? (inside preference).
If so, I will recommend to increase the time or disable it.

4/ Perhaps, disable the check for update may help (preferences too)

Let me know if it helps a bit.

**Comment by Torbaal** [comment]
Hi and thank you for your quick reply.

1/ I'm on Wifi, but on a good connection as far as I can tell : DL at 40 M/s and upload at 20 M/s usually with a ~20 ms ping.
Usage of networf is quiete low for Rolisteam : 68 o reception, 268 receiving when I host (did it for testing, usually I join my DM's)

2/ I had this issue all game long, wich mean for at least 3 to 4 hours. Even after every images where loaded, I still had this issue.
For the record, even when hosting, and with no network usage from Rolisteam, I still have a very bad connection on Team Speak. It improved drastically just by closing Rolisteam.
I do have the notification zone visible.

3/ Heartbeat message was disabled by default. Still is.

4/ Disable it did nothing.

PS : I checked, TS and Rolisteam don't use the same PID.

**Comment by obiwankennedy** [comment]
1/ Have you try to test with wire connection instead of wifi ? It may come from your Wifi driver or hardware which may not like too many connections.

2/ Does your windows is up to date ? 

3/ Did you activate noise cancelation on Teamspeak?

**Comment by Torbaal** [comment]
1/ I can't use wire connection unfortunately. But I'm used to have many connection at the same time : firefox, chrome, TS, Discord, plus online game without issue.

2/ Yes it is.

3/ Yes I did

**Comment by obiwankennedy** [comment]
1/ I could be interesting to give a try once or change the wifi hardware. 

3/ Could you disable it ? For a try ?

**Comment by Torbaal** [comment]
1/ I tried with wire connection, it works perfectly...

3/ I did and changed nothing (Wifi)

4/ Nope

**Comment by obiwankennedy** [comment]
1/ Ok, Could you give me the name of your WIFI hardware ? I would look for informations about issue on it with the technology used in rolisteam.
Perhaps there is a better driver or something.

2/ Let's try with the 1.7.1. 
In the branch 1.8.0, I activated a specific option on the connection. If you can try with rolisteam v1.7.1 and the problem does not occur. We may have a solution.

**Comment by obiwankennedy** [comment]
Another test about the specific option (2):
https://technet.microsoft.com/en-us/library/cc957548.aspx 

If you are capable of changing something in your windows registry. It could be great to increase the time (set it to 0x1388 (5000 millisecond = 5 second), or a even bigger value (0xFFFFFFFF ~= 2hours)

**Comment by Torbaal** [comment]
1/ This is A Realtek USB 3.0 Wireless adaptator 2,4 + 5 Ghz.

2/ I tried with the 1.7.1 and got the same issue.
I've looked at the link you send, but I can't figure how to change that value.

**Comment by obiwankennedy** [comment]
Ok ok, if i'm right we are in the situation: https://bugreports.qt.io/browse/QTBUG-40332

It appears that on wifi one component used by Rolisteam update the wifi network list each 3~4 seconds. Which causes latency. 

Could you start Rolisteam and launch a ping command to any other computer inside your house (you can ping your routeur). And please gives me the time of several line.

We will see if your problem is the same as in this bug report.

-- 
The bad component is QNetworkAccessManager. It is used in several places in Rolisteam.
It is an easy to use component to get information from the web.

So it is used for "image on line", "check your ip", "get information about new version",  even in the note editor it is used.
According to the bug report, QNetworkAccessManager must be created to cause the issue.
Even if you do nothing with it.

If you confirm that behavior, I will be able to give you a version of rolisteam without QNetworkAccessManager. You will lose some small features but you will be able to play.
This component is not used to connect with rolisteam server.

**Comment by Torbaal** [comment]
I've made the test with 2 different adresses. The one from my router, and an other one picked on internet.

The first have a latency of 2 to 3 ms, the other of 379 ms. It shows around 37 ms when I ping google.

I made this test while runing Rolisteam 1.7.1

**Comment by obiwankennedy** [comment]
Hi,

could you put the content of this archive inside the rolisteam v1.8 install directory and make a test ?
It should replace the former rolisteam.exe 

[rolisteam.zip](https://github.com/Rolisteam/rolisteam/files/1468955/rolisteam.zip)

**Comment by Torbaal** [comment]
It works ! \o/

Man, thanks a lot, you've been very concerned, helpfull, and available.

**Comment by obiwankennedy** [comment]
great news!! 

Just keep in mind I disabled several (small) features. 
While you are player it won't affect you so much. As GM you rolisteam experience will be a bit decreased.
