### ISSUE TITLE
Fields on Character sheet won't refresh

### ISSUE THREAD

**Issue by Winthiefow** [Rolisteam/rolisteam#77]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

Rolisteam version: 1.8.2
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
-Open a character sheet in Rolisteam
-Share it with a player
-Player changes some values

#What did you expect to see ? (Make sentences and explains in details with words)
-Values are changed on both Data side and Sheet side

#What did you get instead ? (Describe in details the issue) 
-Values are only changed on Data side. See the change happen on Sheet side require to make a copy of it

**Comment by obiwankennedy** [comment]
Which character sheet did you use ? It may come from it. 
Could you attach it in this report ?

**Comment by Winthiefow** [comment]
Sure, it's a sheet for Warhammer V1, made by me with rcsce

[WarhammerV1.zip](https://github.com/Rolisteam/rolisteam/files/1734316/WarhammerV1.zip)

**Comment by obiwankennedy** [comment]
La fiche est en français donc je réponds en français.

Il n'y a pas de personnages dans la fiche transférée. 
Il n'y a que la structures des champs pour générer la fiche. Si en l'état, je la charge dans rolisteam, rien n'apparait. 

Il convient d'ajouter des personnages à la fiche. Pour chaque personnage, il va falloir donner une valeur au champs. Par défaut, ils sont vides.
Vous pouvez mettre 0 et le répéter par tout. 
Un champs vide ne peut pas être accessible dans la vue ainsi c'est probablement cela qui casse la synchronisation. 

Il faut voir cela comme 4 mondes différents:
Vue MJ <=L1=> Données MJ <=L2=> Données Joueur <=L3=> Vue Joueur

En ayant aucune valeur dans les champs, les liens L1 et L3 ne fonctionneront pas.

# Marche à suivre pour régler le problème.

* Ouvrir la fiche avec RCSE
* Aller dans l'onglet personnage
* Ajouter autant de personnage que de joueur dans la campagne (Une colonne = 1 personnage)
* Éditer une cellule de chaque colonne pour y mettre 0 ou n'importe quel valeur.
* Click droit sur la valeur et dans le menu choisir «applique à tous les champs» (c'est probablement pas le texte exact). L'ensemble des valeurs du personnage sont définis à 0 (ou l'autre valeur).
* Faire la même chose pour tous les personnages.
* Enregistrer
* ouvrir la fiche dans rolisteam, partage un personnage avec un joueur, s'il édite sa fiche et remplace les 0 alors les données vont se mettre à jour.

**Comment by obiwankennedy** [comment]
L'espace cela peut marcher mais si vous avez des cases à cochez elles attendent une valeur numérique (0 ou 1).
