### ISSUE TITLE
[compilation error] [windows only] variables mxKey  and mxOpenKey not declared

### ISSUE THREAD

**Issue by robinmoussu** [Rolisteam/rolisteam#79]
Hello,
I was trying to build rolisteam from source in QtCreator on Windows 10.
I noticed that the commit c2958f87c5613dd34113c4214b718d0516a11582 added in rolisteam/client/main.cpp the following patch:
```
+#ifdef Q_OS_WIN
+    QString cmdLine("\"%1\rolisteam.exe\" \"-l % 1\"");
+    QSettings fooKey("HKEY_CLASSES_ROOT\\rolisteam", QSettings::NativeFormat);
+    mxKey.setValue(".", "URL:rolisteam Protocol");
+    mxKey.setValue("URL Protocol", "");
+    QSettings fooOpenKey("HKEY_CLASSES_ROOT\\rolisteam\\shell\\open\\command", QSettings::NativeFormat);
+    QFileInfo info(QCoreApplication::applicationFilePath());
+    mxOpenKey.setValue(".", cmdLine.arg(info.absoluteFilePath())).replace("% 1","%1");
+#endif
```

I suspect that you forgot to add some part of the file in the commit since `mxKey` and mxOpenKey aren't declared.

**Comment by obiwankennedy** [comment]
Yes,  i did not finish to work around that.  I have to make improvements about reading the custom url first,  then i will fix that.

**Comment by robinmoussu** [comment]
Then don't publish it, especially on master ;)

**Comment by obiwankennedy** [comment]
Sure, but I used to work alone, the "pushing on git" is more an easy way to send data from my linux to my windows than other thing.

**Comment by robinmoussu** [comment]
Just publish on a branch named dev/obiwan or similar, then merge/rebase on top of master when it's ready. The added value for you is that you should be able to identify much more easily what is a "real" commit and what is a "work in progress" commit. Any commit on master are real commits, whereas anything on dev/obiwan can be a wip commit. And obviously, you should fell free to rebase anything in dev/obiwan (since it's really obvious that it's your personal space), whereas you should be careful when doing it on master.

**Comment by obiwankennedy** [comment]
this commit a73d47c5a8a82dcc9225f1174896ce6b361b7b6d  fixes the issue.
