### ISSUE TITLE
Add images into maps

### ISSUE THREAD

**Issue by superllm** [Rolisteam/rolisteam#8]
Hi,

It would be great to add images into maps instead of regular dots (only configurable in size). This could be PC or NPC and will (possibly) lead to a better immersion into the game.

As of the regular dots, these images could be resizeable (in order to match the tiles size) and draggable by players (depending on map's rights).

For the players, they could only choose, for their characters, between a few images authorized by the GM.

For the NPC, the GM can choose any image s⋅he wants to (or from a prepared set of images, far more handy).

Thanks :)

**Comment by obiwankennedy** [comment]
It is already implemented into vmap branch. 
It is scheduled to be part of rolisteam in v1.8.0. Which will be release in long time (2016). In this version, we plan to offer a new kind of map (and other features). The new map system is well-advanced and it already provides some new experiences. But before releasing it, we need to implement other features (character sheet, media manager, etc...)

**Comment by superllm** [comment]
Character sheets ? Wow. That's a huge job if you want to be "cross-game", imo. Or do you plan to do a "character sheet editor" ? That will be awesome.

Can't wait to test it :)

**Comment by Blacky---** [comment]
There is in fact two things: 

1. The ability to add images unto another image/amp, drag them, delete them, etc.

2. The ability to use graphical token, meaning the same token as we have now but with custom images instead of a colored disc.

**Comment by obiwankennedy** [comment]
The two issue has been addressed. (I speak in future but it is already fesable in vmap branch) You will be able to drag and drop images on the map, move them, change size, rotate them, delete them, copy them. 
You may also create character (as PC), define avatar and drop them onto the map. 

For NPC, you will be able to promote and drag/dropped image into character. Then, you will be able to manage all feature of character token. 

I hope it was clear. I plan to make a video sound to describe the new map feature. It will be far from where I want to go before releasing but it will be a good start to get feedbacks.
