### ISSUE TITLE
[compilation error] Cannot find file 'translations/rolisteam_fr.qm'

### ISSUE THREAD

**Issue by robinmoussu** [Rolisteam/rolisteam#80]
Hello, I have the following error while trying to build rolisteam (on Windows 10, with QtCreator).
```RCC: Error in '..\..\rolisteam\rolisteam.qrc': Cannot find file 'translations/rolisteam_fr.qm'```
The file `rolisteam_fr.qm` doesn't exist in the repository. It was last referenced in the commit f517c58989f94906b49c11a69c6650148ae01c04 (and since the name of the commit is "fix rebase", I suspect that you forgot to re-add it, or remove the faulty line in `rolisteam.qrc`).

**Comment by obiwankennedy** [comment]
you have to generate them with lrelease.exe (QtCreator > Tools > External > Linguist > Release

**Comment by robinmoussu** [comment]
Ok, thanks.
