### ISSUE TITLE
Characters sheet not saved while saving scenario

### ISSUE THREAD

**Issue by jlm-gh** [Rolisteam/rolisteam#81]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version : 
*  Linux (Ubuntu 16.04)

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Open scenario
- Modify characters sheet loaded within the scenario
- Save scenario

#What did you expect to see ? (Make sentences and explains in details with words)
- Characters sheet modification saved as I reopen the scenario

#What did you get instead ? (Describe in details the issue) 
- Characters sheet remain unchanged
- If I want to save Characters sheet, I have to save them explicitly with Ctrl+S in .rcs format

**Comment by obiwankennedy** [comment]
This commit fixes the issue: https://github.com/Rolisteam/rolisteam/commit/ae55ab13434c874d6db10c18f8660c8639dfed91

It will be included in v1.9
