### ISSUE TITLE
Player don't see GM's messages in Global

### ISSUE THREAD

**Issue by SneakBug8** [Rolisteam/rolisteam#82]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

Player don't see GM's messages in Global. Other chats work well.

#Your configuration:
Rolisteam version: latest
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
Local GM and Client (2 windows)

![Imgur](https://i.imgur.com/Xu9a6fb.png)

![Imgur](https://i.imgur.com/ci9IZZV.png)

Also, I didn't find a way to pull out the music player window if it's stuck under taskbar. Maybe there is kind of "reset UI" button?

**Comment by obiwankennedy** [comment]
Hi, 
I just want to remind you that you didn't answer my questions about the version you use.
Did the problem occurs again ?

**Comment by SneakBug8** [comment]
I used compiled 1.8.2. Yes, occurs randomly in some cases. Fixes after restart.
