### ISSUE TITLE
Rolisteam 1.8.2 crashes after cancelling "Save scenario as" dialog box

### ISSUE THREAD

**Issue by doct** [Rolisteam/rolisteam#83]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.8.2
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
1. Start Rolisteam
2. Connect to self
3. Click File -> Save Scenario. Dialog box "Save scenario as" opens.
4. close the dialog window using the closer [x] top right or Cancel button, doesn't matter, but without having saved the scenario.
Rolisteam crashes.

#What did you expect to see ? (Make sentences and explains in details with words)
Rolisteam interface.

#What did you get instead ? (Describe in details the issue) 
Rolisteam exits unnormally.

**Comment by obiwankennedy** [comment]
Yes, this bug is known and it is fixed in the current dev branch. 
You will have to wait until the 1.9 to get the fix .
