### ISSUE TITLE
Shortcut Editor

### ISSUE THREAD

**Issue by EtienneCoumont** [Rolisteam/rolisteam#87]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.9.0
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server
* No connection

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Clicked on the menu Edit > Shortcut Editor

#What did you expect to see ? (Make sentences and explains in details with words)
- A window to change shortcuts

#What did you get instead ? (Describe in details the issue) 
- A window that only display shortcuts.

Are shortcuts supposed to be editable ?
I would suggest to remove the menu entry in 1.9.0 (or at least rename it into "shortcut viewer").
And work on a shortcut editor for a future version.

**Comment by obiwankennedy** [comment]
Yes, I will rename the menu entry.

**Comment by EtienneCoumont** [comment]
I can do it.
Do you plan to add shortcut in a future version ?

**Comment by obiwankennedy** [comment]
It is already done, as the other bug you report. But I didn't have time to commit the change. 
The bug about resource manager hid some other issues. I will commit everything tonight. 

What do you means ? 
About shortcut, I'm thinking rework it a bit to add some logic about shortcuts.
What shortcut do you want to see ?
