### ISSUE TITLE
Issues with resources titles

### ISSUE THREAD

**Issue by EtienneCoumont** [Rolisteam/rolisteam#90]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

# Your configuration:
Rolisteam version: 1.9.0 (latest)
Operating System and tools : 
* Windows 10 
* QtCreator 4.6.2
* Qt 5.10.1
* msvc2017 64bits
Mode : GM and host

# What did you do ? (Explain each step from starting rolisteam to the issue)
- I played a bit with resources and resource explorer :

- Map 
  - new >map, enter title, OK. Bug : map is still "untitled" in resource explorer.
  - rename map in resource explorer. Window title is updated, but does not display permissions anymore. Under "window" menu, the entry for the map has old name + permissions.
- Notes
  - new > Note. Save as new file. Resource explorer is updated with new name. 'Window' submenu is not.
  - modify note. window title display a * after the file name. Save. Note is saved but window title still display '*' 
  - rename note in resource explorer. Window title is updated. Change text. Save. BUG : notes are not saved.
- VMap
  - new > vectorial map. enter title, OK. Bug : map is still "untitled" in resource explorer. 'Window' submenu does not display permissions (it is ok but different from simple maps, what is the right behavior ?)
  - rename map in resource eplorer. window title is updated, but does not display permissions anymore.
- Shared Notes
  - I couldn't find a way to save notes
  - rename resource in resource explorer. Window title is updated, but does not display permissions anymore.

# Question
- As vmaps are so great, simple maps become a bit deprecated. Do you plan to remove them in future version ?

**Comment by obiwankennedy** [comment]
I just commit the fix about that. Now, you can rename any file. 

# Future for normal map
Yes, I would like to remove old map. The code is not mine, and it is pretty complex and fragile.

If you want to know which features will comes in next releases, please take a look at : https://docs.google.com/spreadsheets/d/18jDGViuOm6KjqEAumW1RU2qccQQ4-TxiXPtAg0X_M2o/edit#gid=900739263

**Comment by EtienneCoumont** [comment]
Thanks. Nice work ! (and nice roadmap ! :) )

I have checked notes and there was a still issue. I'll make a PR for that.
I will check other points when I get some time.
