### ISSUE TITLE
Crash on dice roll

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rolisteam#97]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version:  1.8.2
Operating System and version (remove irrelevant): 
*  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server
* Player and Client
* Player and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Rolled !((1d8e8+2);(1d6e6+2))mk1

#What did you expect to see ? (Make sentences and explains in details with words)
- Two rolls with dice explosion with a +2 added to the result followed by a keep of the best Roll

#What did you get instead ? (Describe in details the issue) 
Software crashed

I did other test by changing the (), replacing the e<Value< by e[=<value>]
I also tried to set it up as macro...

Lookks like you can't add a bonus or malus to each roll or to the final result you want to be kept.
It's ignored (if added after the mk1) or client crashed if used like described.

We need a way to add modifiers to roll.

Thanks

**Comment by obiwankennedy** [comment]
Yes, the support of instruction is bad in rolisteam v1.8.2.

Have you tried: !1d8e8;1d6e6mk1+2 ? if you add 2 at each dice then no need to make the operation twice and then keep the higher result. 

Anyway, this command does not lead to crash on recent version of the dicesystem.

**Comment by obiwankennedy** [comment]
# 1d8e8+2;1d6e6+2mk1 
I checked a bit, in fact, the k operator expects dice result from previous node. 
the +2 transforms the dice result in scalar result. So K can't operate
So this should not be used.

# 1d8e8;1d6e6mk1+2
It looks to me to be the best solution.
It is working just fine in rolisteam v1.9

**Comment by sioc-de-narf** [comment]
ok, when do we get the 1.9 ?
