### ISSUE TITLE
Character Sheet visual problem

### ISSUE THREAD

**Issue by derpmonog** [Rolisteam/rolisteam#98]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 
Operating System and version (remove irrelevant): 
Windows 10
Rolisteam Setting (remove irrelevant):  

* GM and Client 

#What did you do ? (Explain each step from starting rolisteam to the issue)
-started rolisteam
-loaded custom character sheet
-

#What did you expect to see ? (Make sentences and explains in details with words)
-the character sheet as it is in the editor
-
-

#What did you get instead ? (Describe in details the issue) 
-labels are changed and a button disappeared on the sheet 
-the data section was unchanged
-
in editor
![editor](https://user-images.githubusercontent.com/46627907/51074955-3c395e00-1653-11e9-8a1f-1f1336bf8a47.png)
in app
![49797489_2298541013711483_5861789241234685952_n](https://user-images.githubusercontent.com/46627907/51074911-db118a80-1652-11e9-93da-1ed7007e1be7.png)

**Comment by obiwankennedy** [comment]
RCSE has some issue about adding new field to characters. 
When you create character sheet. You must add character only when you finished to add field.
This issue won't be a problem in future release but for the moment you can give me your rcse file. I will fix it and you will be able to play with it.

Keep in mind, that character sheet in 1.8 was really new.

**Comment by derpmonog** [comment]
Thank you for your response. I appreciate the offer but it was resolved thanks to your help.
